### ISSUE TITLE
Multiomics-BigGIM-DrugResponse updates

### ISSUE THREAD

**Issue by gloriachin** [biothings/pending.api#135]
updated Paser Github repo: [https://github.com/gloriachin/BigGIM_Parser](https://github.com/gloriachin/BigGIM_Parser ) 
commit id: 8e6e26e

Key updates:
1, added new relationships: gene_expressed_in_cell
2, revised xref for mondo
3, added KG sources: cell markers

Request: update the Multiomics-BigGIM-DrugResponse API using the new parser.

@erikyao @colleenXu

**Comment by erikyao** [comment]
@colleenXu API updated

**Comment by gloriachin** [comment]
Updated SmartAPI registration YAML file
https://github.com/gloriachin/translator-api-registry/tree/TRAPI1_3
@colleenXu

**Comment by colleenXu** [comment]
On a basic-level, this issue was addressed. See Guangrong @gloriachin's Translator Slack post [here](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1693423252489259). So I'll close this issue. Guangrong should open a new issue / let us know if anything is needed. 

Here's some Translator Slack posts on the current situation / where things were left off: 
* [my sense of where we were at](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1692858915279099?thread_ts=1692655035.536169&cid=C022EL8D3AB) 
* [there's likely a problem w/ one of the added x-bte operations](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1692861042887999?thread_ts=1692655035.536169&cid=C022EL8D3AB), see https://github.com/NCATS-Tangerine/translator-api-registry/blob/2ec8ad25c7797a365212fe6c8e76eed65754c2a0/drug_response_kp/smartapi.yaml#L642 @gloriachin 
* SmartAPI registration for this API was transferred to Guangrong https://github.com/SmartAPI/smartAPI/issues/200
