### ISSUE TITLE
CHEMBL IDs for drug response kp api

### ISSUE THREAD

**Issue by colleenXu** [biothings/pending.api#56]
currently the parser is handling these IDs incorrectly. These IDs are only for the objects. 

Current data:
* we want to keep records with IDs in this format: `CHEMBL:CHEMBL261849`
* we don't want to keep records with IDs in this format: `CHEMBL:3137320`. These seem to be duplications of other rows (that have the first ID format above)

so we want to take records with IDs like `CHEMBL:CHEMBL261849` and end up with records in the API that...
* Have a field with the key CHEMBL_COMPOUND (note the _ here!) and the value as the ID (CHEMBL261849)
* Have a field with the key id and the value with the whole curie (CHEMBL.COMPOUND:CHEMBL3137320)

Example:
```
"object": {
    "CHEMBL_COMPOUND": "CHEMBL3137320", 
    "id": "CHEMBL.COMPOUND:CHEMBL3137320",
    "name": "BMN-673",
    "type": "biolink:SmallMolecule"
}
```

But right now, the records look like this, which means there's a bug involving how the "CHEMBL" sub-string is handled for the id and `CHEMBL_COMPOUND` values...:

```
"object": {
    "CHEMBL_COMPOUND": "CHEMBL.COMPOUND3137320", 
    "id": "CHEMBL.COMPOUND:CHEMBL.COMPOUND3137320",
    "name": "BMN-673",
    "type": "biolink:SmallMolecule"
}
```

**Comment by erikyao** [comment]
## Problems in Current Data File

File in use: [Table_DrugResponse_KP_v2021.11.21_rm_redundance_v2022.2.25.csv.gz](https://storage.googleapis.com/multiomics_provider_kp_data/drug_response/Table_DrugResponse_KP_v2021.11.21_rm_redundance_v2022.2.25.csv.gz)

First, it's better to discuss subject IDs (1st column, _Subject_Ensembl_gene_ID_) and object IDs (8th column, _Object_id_) separately since they are troublesome in different ways.

### 1. _Subject_Ensembl_gene_ID_ Problems

As the column name suggests, ENSEMBL IDs are expected. Most are formatted as `ENSEMBL:<ENSG_NUM>` such as `ENSEMBL:ENSG00000103226`.

However I found some outliners.

#### 1.1 Empty Values

Such as Line 1604 and 1605:

```txt
CRIPAK,,Entrez:,Symbol:CRIPAK,Gene,CCT007093,CCT007093,PUBCHEM:2314623,ChemicalSubstance,biolink:associated with sensitivity to,Genetic variants,IC50,T-test,0.018541804,effect_size,-1.680107563,26,ALL,MONDO:0004967,GDSC,PMID: 27397505,Multiomics-BigGIM
CRIPAK,,Entrez:,Symbol:CRIPAK,Gene,AZD6482,AZD6482,CHEBI:91359,ChemicalSubstance,biolink:associated with sensitivity to,Genetic variants,IC50,T-test,0.001435684,effect_size,-2.298233273,26,ALL,MONDO:0004967,GDSC,PMID: 27397505,Multiomics-BigGIM
```

**Possible Fix:** ignore such lines

#### 1.2 ENSG Numbers w/o ENSEMBL Namespace

Such as `ENSG00000265590` in line 240731:

```txt
LINC00846,ENSG00000265590,Entrez:,Symbol:LINC00846,Gene,KIN001-102,KIN001-102,HMS_LINCS_ID:10035-101,ChemicalSubstance,biolink:associated with sensitivity to,Expression,AUC,Spearman_correlation,0.045946566581951453,correlation_coeffienct,-0.42970073404856013,22,ALL,MONDO:0004967,GDSC,PMID: 27397505,Multiomics-BigGIM
```

**Possible Fix:** for any given ID, its namespace is detected by splitting on colons. If the splitting fails and the ID starts with `ENSG`, we can automatically put it under ENSEMBL namespace.

**N.B.:** `ENSG00000265590` appears 336 times in this file and this is the only unique value for this type of outliners.

#### 1.3 Mixed ENSEMBL and Entrez Namespaces

E.g. `ENSEMBL:Entrez:84953` in line 2749:

```txt
MICALCL,ENSEMBL:Entrez:84953,Entrez:,Symbol:MICALCL,Gene,VX-702,VX-702,PUBCHEM:10341154,ChemicalSubstance,biolink:associated with sensitivity to,Genetic variants,IC50,T-test,0.021502704,effect_size,-1.723972288,26,ALL,MONDO:0004967,GDSC,PMID: 27397505,Multiomics-BigGIM
```

**Possible Fix:** Update the source file or I would simply ignore it for now. The column name is _Subject_Ensembl_gene_ID_ so I would not accept an Entrez ID as an valid value.

**N.B.:** `ENSEMBL:Entrez:84953` appears 361 times in this file and this is the only unique value for this type of outliners.

### 2. _Object_id_ Problems

_Object_id_ column is well formatted so splitting on colons goes smoothly. Five namespaces are presented:

```python
{'PUBCHEM', 'CHEMBL_COMPOUND', 'CHEBI', 'CID', 'HMS_LINCS_ID'}
```

However @colleenXu suggested:

> they are not using curie prefixes that are valid based on Translator/biolink model:
> - they are using 'PUBCHEM' and 'CID'....both seem to actually be PUBCHEM.COMPOUND
> - they are using 'HMS_LINCS_ID' which isn't even in the biolink model

**Possible Fix:** Some rules of converting these prefixes are required here

**Comment by colleenXu** [comment]
for 1.2: note that ENSG00000265590 does have an [NCBIGene / Entrez ID (110091775)](https://www.ncbi.nlm.nih.gov/gene/110091775) and a [mapped HGNC ID](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:54636). However....it's not exactly a gene....(it corresponds to a "readthrough" region of the genome with multiple genes, that are all transcribed to 1 big transcript. Then separate proteins may be translated....or a "fusion" protein that corresponds to those multiple genes).

**Comment by erikyao** [comment]
Chunlei's suggestion:

> ... all three issues you listed for the “subject_id” I think are the data issue, we should let them fix (and skip on our end for now). Don’t think we want to put too much efforts to fix them.
> 
> For the prefix issue on object_id , we should also ask them to fix eventually, but it’s easy enough for us to fix it quickly in our code, so I am ok to make that fix for them.
> 
> the unknown prefix like HMS_LINCS_ID , we should also let them know, most likely this is case biolink does not contain that id type yet, so we should import them as it is. BTE can still report them, but there is no way this id will be able to link with any other APIs (which is fine for their API actually) 

Colleen's suggestion:

> this is my understanding of the prefixes in the data vs the Translator standard. Ideally, I think we can handle this in the parser. However, there's some confusion in the object prefixes used right now....so maybe it's worth fixing that confusion first (see the first point below)
> - PUBCHEM or CID -> PUBCHEM.COMPOUND. The ID should be a number.....I think ideally the data wouldn't be using both prefixes to talk about the same thing....unless it's sometimes not the same namespace?
> - CHEMBL -> CHEMBL.COMPOUND. However, all IDs should also start with CHEMBL and then there's a number
> - CHEBI: fine. The ID should be a number.
> - HMS_LINCS_ID: I don't see this kind of ID in https://registry.identifiers.org/registry. It would help to put the Biolink-model people on this. Does "HMS LINCS ID" have cross-mappings to other ID namespaces? What prefix/id-format should Translator use - like should we keep the hyphens in the IDs?

**Comment by colleenXu** [comment]
@erikyao we may be able to close this issue now?
