### ISSUE TITLE
Data source: RaMP

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#69]
name: RaMP (Relational database of Metabolomic Pathways)
url: https://rampdb.nih.gov/
download: 
     https://rampdb.nih.gov/about
     https://figshare.com/articles/dataset/RaMP_Database_MySQL_Dump_v2_0_7_20220428/19674540
license: GPL v2

**Comment by andrewsu** [comment]
From https://rampdb.nih.gov/about, I'm wondering if we already get many/most of these resources from the primary source?
![image](https://user-images.githubusercontent.com/2635409/175462703-e3bab5e0-64f1-46ae-add5-477ad3bec9c8.png)

**Comment by andrewsu** [comment]
@colleenXu [pointed out](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/372#issuecomment-1129556591) that RaMP has an [API](https://rampdb.nih.gov/api). Given [Translator interest](https://github.com/NCATSTranslator/Feedback/issues/64) in this data source, let's look at generating a SmartAPI annotation...

**Comment by colleenXu** [comment]
With earlier post in that issue https://github.com/biothings/BioThings_Explorer_TRAPI/issues/372#issuecomment-1036586086

**Comment by colleenXu** [comment]
### Info

RaMP's github repo has two SmartAPI yamls; it's not clear which one we'd want to edit.

* [this one](https://github.com/ncats/RaMP-Client/blob/master/libs/features/ramp/ramp-api/src/assets/data/ramp_openapi_with_extensions.yml) appears to be used by https://rampdb.nih.gov/api (since both have one server url, RaMP as info.contact.name)
* [this](https://github.com/ncats/RaMP-Client/blob/master/apps/ramp-server/ramp_openapi_with_extensions.yml) is a slightly older version based on the commit history

I'm working on a [forked](https://github.com/colleenXu/RaMP-Client) version of the first option above.

### Other endpoints

There are also endpoints that look interesting, but we can't annotate them because they don't use IDs as inputs or as outputs

* `analytes-from-pathways`: takes pathway names as input, not IDs. Output: `Gene` or `SmallMolecule` (chemical/metabolite). Should retrieve same info/opposite-direction compared to `pathways-from-analytes`. 
* `ontologies-from-metabolites` / `metabolites-from-ontologies`: interesting, but the ontologies are human-readable labels with no IDs
    * health condition
    * found in what subcellular location
    * found in what tissue/substructure, organ/component
    * perhaps more a node attribute (wouldn't annotate for associations)
        * found in what biofluid/excreta 
        * found in what source in the world
        * used in what industrial application

**Comment by colleenXu** [comment]
### Issues writing x-bte annotation

There are endpoints that meet our criteria (relationships between entities, entities have IDs), but we encounter issues parsing their responses. 

I think these issues can be addressed with post-query processing, perhaps with the [api-response-transform module](https://github.com/biothings/api-respone-transform.js) (custom handler) or [JQ](https://github.com/biothings/api-respone-transform.js/pull/38) (which hasn't been incorporated into BTE yet... )

#### `pathways-from-analytes`

* ISSUE 1: the output ID field `data.pathwayId` value can be a WIKIPATHWAYS, REACT, or KEGG.PATHWAY ID (I'm not sure if it can be others). BTE then has trouble correctly processing this output, similar to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/585
    * note: these IDs don't have prefixes, but the value of the `data.pathwaySource` seems to correspond to the ID-namespace for each record (values seem to be `wiki`, `reactome`, or `kegg`). Perhaps JQ list-filter could help in this particular case
* ISSUE 2: would have the batch-querying processing issue similar to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/584. The matching input is provided in the `data.inputID` field (using RaMP's format for prefix-spelling / capitalization) 

<details>
<summary>Example of API response with 3 different output ID-namespaces</summary>

```
    {
      "pathwayName": "7q11.23 copy number variation syndrome",
      "pathwaySource": "wiki",
      "pathwayId": "WP4932",
      "inputId": "hmdb:HMDB0000148",
      "commonName": "Glutamate; L-Glutamic acid"
    },
    {
      "pathwayName": "Activation of AMPA receptors",
      "pathwaySource": "reactome",
      "pathwayId": "R-HSA-399710",
      "inputId": "hmdb:HMDB0000148",
      "commonName": "Glutamate; L-Glutamic acid"
    },

    {
      "pathwayName": "Glycine, serine and threonine metabolism",
      "pathwaySource": "kegg",
      "pathwayId": "map00260",
      "inputId": "hmdb:HMDB0000148",
      "commonName": "Glutamate; L-Glutamic acid"
    },
```

</details>

<details>
<summary>Example of API response starting with 2 different input IDs</summary>

```
    {
      "pathwayName": "Glycine, serine and threonine metabolism",
      "pathwaySource": "kegg",
      "pathwayId": "map00260",
      "inputId": "hmdb:HMDB0000064",
      "commonName": "Creatine"
    },
    {
      "pathwayName": "Glycine, serine and threonine metabolism",
      "pathwaySource": "kegg",
      "pathwayId": "map00260",
      "inputId": "hmdb:HMDB0000148",
      "commonName": "Glutamate; L-Glutamic acid"
    },
```

</details>


#### `common-reaction-analytes`

The endpoint seems to provide gene -> chem (gene2met) and chem -> gene (met2gene) that are involved in the same reaction. We'd want to confirm this (note that what reaction/pathway they're both in...isn't provided)

* ISSUE 3: the output ID field `data.rxn_partner_ids` value is a `;`-delimited string of the entity's IDs in multiple ID-namespaces, all using RaMP's ID-prefix spellings
    * would like to separate these IDs by namespace
* also would have ISSUE 2 (batch-querying). The matching input is provided in the `data.input_analyte` field (using RaMP's format for prefix-spelling / capitalization) 

<details>
<summary>Example output from two chemical input IDs</summary>

```
    {
      "query_relation": "met2gene",
      "input_analyte": "hmdb:HMDB0000148",
      "input_common_names": "Glutamate; L-Glutamic acid",
      "rxn_partner_common_name": "PPAT",
      "rxn_partner_ids": "ensembl:ENSG00000128059; entrez:5471; gene_symbol:PPAT; hmdb:HMDBP00331; uniprot:A8K4H7; uniprot:D6RCC8; uniprot:D6RE15; uniprot:Q06203"
    },


    {
      "query_relation": "met2gene",
      "input_analyte": "hmdb:HMDB0000064",
      "input_common_names": "Creatine",
      "rxn_partner_common_name": "CKMT2",
      "rxn_partner_ids": "ensembl:ENSG00000131730; entrez:1160; gene_symbol:CKMT2; hmdb:HMDBP00719; uniprot:A0A024RAK5; uniprot:D6R998; uniprot:D6RHV3; uniprot:P17540"
    },
```

</details>

**Comment by colleenXu** [comment]
I have the work I've done so far in this fork: https://github.com/colleenXu/RaMP-Client/blob/x-bte-annotation/libs/features/ramp/ramp-api/src/assets/data/ramp_openapi_with_extensions.yml

I annotated the `pathways-from-analytes` endpoint for `HMDB SmallMolecule -> REACT Pathway` and `NCBIGene Gene -> REACT Pathway`. I tested in with prod/test code and main branch code for BTE and it "works", BUT it has ISSUE 1 described in the previous post (so the responses have nodes with incorrectly-formatted IDs because the IDs are actually `KEGG.PATHWAY` or `WIKIPATHWAYS` and not `REACT`).

**Comment by colleenXu** [comment]
Note that I've updated this [comment](https://github.com/biothings/pending.api/issues/69#issuecomment-1474740449)

**Comment by colleenXu** [comment]
Closing in favor of https://github.com/biothings/biothings_explorer/issues/705, because (1) we seem to have decided to NOT make a pending BioThings API from this data and (2) it's easier to track this effort using the BioThings Explorer repo's tags. 

However, the info in this issue are the basis of that issue.
