### ISSUE TITLE
web ui: example queries should escape colon character in the query term

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#74]
Here is an example:

https://biothings.ncats.io/rhea/query?q=citations:PMID:18949503

from:

https://biothings.ncats.io/rhea/

the correct query should escape the `:`:

https://biothings.ncats.io/rhea/query?q=citations:PMID\:18949503

**Comment by marcodarko** [comment]
Will be addressed in https://github.com/biothings/pending.api/pull/78

**Comment by andrewsu** [comment]
Just noting that #78 was merged, but it looks like the issue is not fixed.  https://biothings.ncats.io/rhea/ generated this example query:

https://biothings.ncats.io/rhea/query?q=children_rheas:RHEA:12718

which should be one of these variants:

https://biothings.ncats.io/rhea/query?q=children_rheas:RHEA\:12718
https://biothings.ncats.io/rhea/query?q=children_rheas:%22RHEA:12718%22

**Comment by newgene** [comment]
tagging @marcodarko to look into this issue.

**Comment by marcodarko** [comment]
I do see that some point I took care of that issue by escaping colons but then later revised it and now it should enclose the values with special characters in parentheses to avoid issues like this.  I think the prod code perhaps might be missing this update (??) but regardless a different issue will be fixed in my next PR and we can see if this resolves itself because I do see that in my local machine this generates valid queries without issues. 

<img width="707" alt="Screen Shot 2023-07-24 at 3 01 19 PM" src="https://github.com/biothings/pending.api/assets/23092057/b4c3fa72-fbe3-44d5-8b87-1768403c24a9">

**Comment by marcodarko** [comment]
Will be addressed in https://github.com/biothings/pending.api/pull/134

**Comment by newgene** [comment]
fixed in merged #134
