### ISSUE TITLE
Update `clinical_risk_kp` and change the API name to `multiomics_ehr_risk_kp `

### ISSUE THREAD

**Issue by erikyao** [biothings/pending.api#76]
Requirement from: @colleenXu and [Basazin Belhu](https://app.slack.com/team/U035CMVEW3W)

**Comment by erikyao** [comment]
Done with commit 84de7d0ab83bfb6837dd26da3f67db8cd6c870eb

First release after renaming:

- Source: `clinical_risk_kp` (The repo name is kept for BTE compatibility. Ask @colleenXu for details)
  - Plugin: https://github.com/Hadlock-Lab/clinical_risk_kp
  - Git: HEAD (057a5e1dd837499aaf0e20669b21dda6b05dcb34)
- Build: `multiomics_ehr_risk_kp_20220729_y5q7xaxe`
- API: https://biothings.ncats.io/multiomics_ehr_risk_kp

**Comment by colleenXu** [comment]
To clarify: the github repo has to keep the name it has, because if it is renamed, the url to the SmartAPI yaml for the API is changed. This will break the registration, and it'll have to be re-registered. That'll change the URLs used to access the API through BTE, which will be a pain for the other Translator tools that use this...
